#!/bin/bash
# python src/eqmodel_test.py --shift_window=1.7
# python src/eqmodel_test.py --shift_window=1.6
# python src/eqmodel_test.py --shift_window=1.5
# python src/eqmodel_test.py --shift_window=1.4
# python src/eqmodel_test.py --shift_window=1.3
# python src/eqmodel_test.py --shift_window=1.2
# python src/eqmodel_test.py --shift_window=1.1

python src/eqmodel_test.py --shift_window=3
python src/eqmodel_test.py --shift_window=4
python src/eqmodel_test.py --shift_window=5
python src/eqmodel_test.py --shift_window=6
python src/eqmodel_test.py --shift_window=7
python src/eqmodel_test.py --shift_window=8
python src/eqmodel_test.py --shift_window=9
python src/eqmodel_test.py --shift_window=10
python src/eqmodel_test.py --shift_window=12
python src/eqmodel_test.py --shift_window=15
python src/eqmodel_test.py --shift_window=20
python src/eqmodel_test.py --shift_window=30

# python src/eqmodel_test.py --shift_window=1
# python src/eqmodel_test.py --shift_window=0.9
# python src/eqmodel_test.py --shift_window=0.8
# python src/eqmodel_test.py --shift_window=0.7
# python src/eqmodel_test.py --shift_window=0.6
# python src/eqmodel_test.py --shift_window=0.5
# python src/eqmodel_test.py --shift_window=0.4
# python src/eqmodel_test.py --shift_window=0.3
# python src/eqmodel_test.py --shift_window=0.2
# python src/eqmodel_test.py --shift_window=0.1
# python src/eqmodel_test.py --shift_window=0
# python src/eqmodel_test.py --shift_window=-0.1
# python src/eqmodel_test.py --shift_window=-0.2
# python src/eqmodel_test.py --shift_window=-0.3
# python src/eqmodel_test.py --shift_window=-0.4
# python src/eqmodel_test.py --shift_window=-0.5
# python src/eqmodel_test.py --shift_window=-0.6
# python src/eqmodel_test.py --shift_window=-0.7
# python src/eqmodel_test.py --shift_window=-0.8
# python src/eqmodel_test.py --shift_window=-0.9
# python src/eqmodel_test.py --shift_window=-1
# python src/eqmodel_test.py --shift_window=-1.1
# python src/eqmodel_test.py --shift_window=-1.2
# python src/eqmodel_test.py --shift_window=-1.3
# python src/eqmodel_test.py --shift_window=-1.4
# python src/eqmodel_test.py --shift_window=-1.5
# python src/eqmodel_test.py --shift_window=-1.6
# python src/eqmodel_test.py --shift_window=-1.7
# python src/eqmodel_test.py --shift_window=-1.8
# python src/eqmodel_test.py --shift_window=-1.9
# python src/eqmodel_test.py --shift_window=-2